object ColumnNames {
  val USER_NAME: String = "user_name"
  val USER_FOLLOWERS: String = "user_followers"
  val USER_LOCATION: String = "user_location"
  val DATE: String = "date"
  val USER_CREATED: String = "user_created"
  val USER_FAVOURITES: String = "user_favourites"
  val USER_FRIENDS: String = "user_friends"
  val USER_VERIFIED: String = "user_verified"
  val HASHTAGS: String = "hashtags"
  val COUNT: String = "count"
  val AVERAGE_FOLLOWERS: String = "average_followers"
  val TEXT = "text"
  val IS_RETWEET = "is_retweet"
}